name: NPM Cache and INstall dependencies
descritption: NPM Cache and INstall dependencies
author: @mdasifnasin
inputs:
    path_of_the_file:
        requrired: true
runs:
    using:
        composite
    steps:
      - name: Cache NPM dependencies
        uses: actions/cache@v4.2.0
          with:
            path: ${{inputs.path_of_the_file}}
            key: ${{ runner.os}}-node_modules-${{ hashFiles('package-lock.json')}}
      - name: Installing Dependencies
        run: |
          npm -v
          node -v
          npm install