name: Solar-Sytem-Unit-Testin
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
      - "feature/*"
env:
  MONGO_URI: "mongo+srv://supercluster.d83jj.mongodb.net/superData"
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}
jobs:
  Unit-Testing:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [18]
        # exclude:
        #   - os: windows-latest
        #   - version: [18,20,22]
    # concurrency: 
    #   cancel-in-progress: false
    #   group: prodnpm install
    
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Setting up Node JS
        uses: actions/checkout@v4.2.2
        with:
          node-version: ${{matrix.version}}
      
      - name: Installing Dependencies
        run: |
          npm -v
          node -v
          npm install

      - name: Testing the App
        timeout-minutes: 3
        run: npm test


      - name: Upload the artifacts.10th
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: test-results.xml

  Code_Coverage:
    needs: Unit-Testing
    name: Code Coverage Test
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest]
    # # concurrency: 
    # #   cancel-in-progress: false
    # #   group: prodnpm install
    
    # runs-on: ${{matrix.os}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Setting up Node JS
        uses: actions/checkout@v4.2.2
        with:
          node-version: '18'
      
      - name: Installing Dependencies
        run: |
          npm -v
          node -v
          npm install

      - name: Testing the App
        timeout-minutes: 3
        run: npm test

      - name: Test Coverage
        timeout-minutes: 3
        run: |
          npm run coverage
          exit 1

      - name: Upload the artifacts.10th
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          retention-days: 5