name: Solar-Sytem-Unit-Testin
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
      - "feature/*"

jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Setting up Node JS
        uses: actions/checkout@v4.2.2
        with:
          node-version: '18'
      
      - name: Installing Dependencies
        run: |
          npm -v
          node -v
          npm install

      - name: Testing the App
        run: npm test